### ISSUE TITLE
Error in eclipse instance without papyrus plugin

### ISSUE THREAD

**Issue by thomcz** [Cooperate-Project/PlantUMLPrinterParser#8]
If you install the plugin from the [bintray update site](https://dl.bintray.com/cooperate-project/Notation2Plant/latest/) without instaling the papyrus plugin the following error occour: 
Failed to create the part's controls
There should be a better error message or include the papyrus plugin to the update sit

**Comment by seiferma** [comment]
This issue has already been fixed with [Commit a21023a](https://github.com/Cooperate-Project/PlantUMLPrinterParser/commit/a21023ade6f78b750f12b7cbe2fceeaf79165101), hasn't it?
